
//AUTH TYPES
export const SET_LOADING_USER = 'SET_LOADING_USER'; 
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const SET_USER_ERRORS = 'SET_USER_ERRORS';
export const CLEAR_USER_ERRORS = 'CLEAR_AUTH_ERRORS';
export const MARK_NOTIFICATION_AS_READ = 'MARK_NOTIFICATION_AS_READ';

//UI REDUCER TYPES
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const OPEN_ERRORS_DIALOG = 'OPEN_ERRORS_DIALOG';
export const ACTIVATE_LINEAR_PROGRESS = 'ACTIVATE_LINEAR_PROGRESS';
export const DEACTIVATE_LINEAR_PROGRESS = 'DEACTIVATE_LINEAR_PROGRESS';
export const OPEN_USER_DETAILS_DIALOG = 'OPEN_USER_DETAILS_DIALOG';
export const OPEN_CHAT_MODAL = 'OPEN_CHAT_MODAL';

//POST TYPES
export const SET_POSTS = 'SET_POSTS';
export const SET_USER_VISITED_POSTS = 'SET_USER_VISITED_POSTS';
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED';
export const REFRESH_SINGLE_POST = 'REFRESH_SINGLE_POST';
export const REFRESH_VISITED_USER_POST = 'REFRESH_VISITED_USER_POST';
export const DELETE_POST = 'DELETE_POST';
export const SET_TOTAL_POSTS = 'SET_TOTAL_POSTS';

//SOCKET GLOBAL
export const SET_SOCKET_GLOBAL_OBJECT = 'SET_SOCKET_GLOBAL_OBJECT';

//VISITED USER
export const SET_VISITED_USER = 'SET_VISITED_USER';
export const SET_VISITED_USER_ERRORS = 'SET_VISITED_USER_ERRORS';
export const SET_VISITED_USER_POSTS = 'SET_VISITED_USER_POSTS';
export const SET_TOTAL_VISITED_USER_POSTS = 'SET_TOTAL_VISITED_USER_POSTS';
export const CLEAR_VISITED_USER_DATA = 'CLEAR_VISITED_USER_DATA';

//CHAT USER
export const SET_CHAT_USER_DATA = 'SET_CHAT_USER_DATA';
export const CLEAR_CHAT_USER_DATA = 'CLEAR_CHAT_USER_DATA'

//MESSAGES
export const SET_MESSAGES = 'SET_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const CLEAR_MESSAGES = 'CLEAN_MESSAGES';
export const SET_TOTAL_MESSAGES = 'SET_TOTAL_MESSAGES';

//USERS
export const SET_USERS = 'SET_USERS';
export const SET_ONLINE_USERS = 'SET_ONLINE_USERS';
export const SET_POSTS_LIMIT = 'SET_POSTS_LIMIT';
