
//AUTH TYPES
export const SET_LOADING_USER = 'SET_LOADING_USER'; 
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const SET_USER_ERRORS = 'SET_USER_ERRORS';
export const CLEAR_USER_ERRORS = 'CLEAR_AUTH_ERRORS';

//UI REDUCER TYPES
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const OPEN_ERRORS_DIALOG = 'OPEN_ERRORS_DIALOG';
export const ACTIVATE_LINEAR_PROGRESS = 'ACTIVATE_LINEAR_PROGRESS';
export const DEACTIVATE_LINEAR_PROGRESS = 'DEACTIVATE_LINEAR_PROGRESS';
export const OPEN_USER_DETAILS_DIALOG = 'OPEN_USER_DETAILS_DIALOG';

//POST TYPES
export const SET_POSTS = 'SET_POSTS';
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED';
export const REFRESH_SINGLE_POST = 'REFRESH_SINGLE_POST';
export const DELETE_POST = 'DELETE_POST';

//SOCKET GLOBAL
export const SET_SOCKET_GLOBAL_OBJECT = 'SET_SOCKET_GLOBAL_OBJECT';