
//AUTH TYPES
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';

//UI REDUCER TYPES
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const OPEN_ERRORS_DIALOG = 'OPEN_ERRORS_DIALOG';
//DATA REDUCER TYPES
